// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ProductManagement.Core.Models;
using System;

namespace ProductManagement.Core.Models.Configurations
{
    public partial class CategoriesMetadatumConfiguration : IEntityTypeConfiguration<CategoriesMetadatum>
    {
        public void Configure(EntityTypeBuilder<CategoriesMetadatum> entity)
        {
            entity.HasKey(e => e.MetadataId)
                .HasName("PK_CategoriesMetadata_1");

            entity.HasIndex(e => new { e.CatId, e.MetadataText }, "IX_CategoriesMetadata")
                .IsUnique();

            entity.Property(e => e.MetadataId).HasColumnName("Metadata_Id");

            entity.Property(e => e.CatId).HasColumnName("Cat_Id");

            entity.Property(e => e.MetadataText)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("Metadata_Text");

            entity.HasOne(d => d.Cat)
                .WithMany(p => p.CategoriesMetadata)
                .HasForeignKey(d => d.CatId)
                .HasConstraintName("FK_CategoriesMetadata_Categories");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CategoriesMetadatum> entity);
    }
}
