// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ProductManagement.Core.Models;
using System;

namespace ProductManagement.Core.Models.Configurations
{
    public partial class CategoryConfiguration : IEntityTypeConfiguration<Category>
    {
        public void Configure(EntityTypeBuilder<Category> entity)
        {
            entity.HasKey(e => e.CatId);

            entity.HasIndex(e => e.Name, "IX_Categories")
                .IsUnique();

            entity.Property(e => e.CatId).HasColumnName("Cat_Id");

            entity.Property(e => e.Name).HasMaxLength(150);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Category> entity);
    }
}
