// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using ProductManagement.Core.Models;
using System;

namespace ProductManagement.Core.Models.Configurations
{
    public partial class ProductsMetadatumConfiguration : IEntityTypeConfiguration<ProductsMetadatum>
    {
        public void Configure(EntityTypeBuilder<ProductsMetadatum> entity)
        {
            entity.HasKey(e => e.ProdMetaId);

            entity.HasIndex(e => new { e.ProdId, e.MetadataId }, "IX_ProductsMetadata")
                .IsUnique();

            entity.Property(e => e.ProdMetaId).HasColumnName("prodMeta_Id");

            entity.Property(e => e.MetadataId).HasColumnName("Metadata_Id");

            entity.Property(e => e.ProdId).HasColumnName("Prod_Id");

            entity.HasOne(d => d.Metadata)
                .WithMany(p => p.ProductsMetadata)
                .HasForeignKey(d => d.MetadataId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductsMetadata_CategoriesMetadata");

            entity.HasOne(d => d.Prod)
                .WithMany(p => p.ProductsMetadata)
                .HasForeignKey(d => d.ProdId)
                .HasConstraintName("FK_ProductsMetadata_Products");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductsMetadatum> entity);
    }
}
