// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductManagement.Core.Models
{
    public partial class Category
    {
        public Category()
        {
            CategoriesMetadata = new HashSet<CategoriesMetadatum>();
            Products = new HashSet<Product>();
        }

        public int CatId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<CategoriesMetadatum> CategoriesMetadata { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}