// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductManagement.Core.Models
{
    public partial class ProductsMetadatum
    {
        public int ProdMetaId { get; set; }
        public int ProdId { get; set; }
        public int MetadataId { get; set; }

        public virtual CategoriesMetadatum Metadata { get; set; }
        public virtual Product Prod { get; set; }
    }
}