// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductManagement.Core.Models
{
    public partial class Product
    {
        public Product()
        {
            ProductsMetadata = new HashSet<ProductsMetadatum>();
        }

        public int ProdId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public DateTime CreatedAt { get; set; }
        public int CategoryId { get; set; }
        public bool IsArchived { get; set; }

        public virtual Category Category { get; set; }
        public virtual ICollection<ProductsMetadatum> ProductsMetadata { get; set; }
    }
}