// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductManagement.Core.Models
{
    public partial class Role
    {
        public Role()
        {
            UserRoles = new HashSet<UserRole>();
        }

        public Guid RoleId { get; set; } = Guid.NewGuid();

        public string Name { get; set; }

        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}